services:
- type: web
  name: n8n
  env:
  - key: N8N_HOST
    value: 0.0.0.0
  - key: N8N_PORT
    value: 8080
  - key: N8N_EXECUTIONS_MODE
    value: queue
  - key: N8N_WORKFLOWS_PATH
    value: /home/node/.n8n
  - key: N8N_CONTENT_PATH
    value: /home/node/.n8n
  buildCommand: yarn install && yarn build
  startCommand: yarn start
  disk:
    size: 1024
    mountPath: /home/node/.n8n
