services:
  - type: web
    name: n8n-web
    env: node
    buildCommand: npm install -g n8n
    startCommand: n8n start --port=$PORT
    envVars:
      - key: N8N_WORKER_TYPE
        value: web
      - key: N8N_BASIC_AUTH_USER
        value: madman69
      - key: N8N_BASIC_AUTH_PASSWORD
        value: aV@.H@W*5QDcL4V

  - type: worker
    name: n8n-worker
    env: node
    buildCommand: npm install -g n8n
    startCommand: n8n start
    envVars:
      - key: N8N_WORKER_TYPE
        value: main
